### ISSUE TITLE
OpenAQ Code of Conduct

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-info#2]
@masalmon - I'm thinking we should add in a link to the [FAQs](https://github.com/openaq/openaq-info/blob/master/FAQ.md) on the OpenAQ Code of Conduct you developed once it is housed somewhere in GitHub. Thoughts? Sound okay?

Will also link your Google Doc draft here for now, with your permission.

**Comment by masalmon** [comment]
Ok!

Where should the coc be exactly by the way in your opinion ?

**Comment by RocketD0g** [comment]
Cool! Thinking it should be in the openaq-info section? We can always move later, if not a good spot. In fact, just posting in here now from google doc, cc'ing you.

**Comment by RocketD0g** [comment]
(@masalmon - See new FAQ #8)

**Comment by masalmon** [comment]
Great, thanks a lot. It's nearly a shame to be listed as the original drafter when what I did was mostly copy-pasting :grinning: Do you want to Slack/Tweet about the code of conduct?
