### ISSUE TITLE
Collaboration with luftdaten.info

### ISSUE THREAD

**Issue by DonPavlov** [openaq/openaq-info#3]
Are you already collaborating with the german project luftdaten.info? It does the same on a much finer scale. By using the community to build the sensors themselves, they control the data much better. Make much more measurements. During low and peek times not only once per day, like in many german cities.
I think collaboration of these two projects would be great. If not already happening.

edit: Also i think, you can try contacting them in english. Germans are quite known for beeing proficient in this language.

**Comment by RocketD0g** [comment]
I have to say, @dehein, this GH issue clearly dropped off my radar. To follow up very belatedly - we have talked with the fantastic folks at luftdaten.info. We are actively looking for ways to collaborate, both technically and through our communities - there are so many synergistic points. We still don't have capacity to add in this type of data yet, but we are looking for funding to do so.
